### PR TITLE
Make the payment description more generic

### PR DESCRIPTION
**Pull request by nolim1t**
Make the payment description more generic

### CODE REVIEW

**Comment by nolim1t** [comment]
feel free to suggest a better way of doing this, you may push commits into the branch supporting this PR

**Comment by hitchcott** [comment]
I think for the demo it should be Food4Thought, but then configurable for other deployments?

**Comment by nolim1t** [comment]
Make it default to LNCM but change it before you build

**Comment by hitchcott** [comment]
Agree(ish).

But this is part of a larger discussion about how we do deployments.

There should probably be a whitelabel version, which can then be forked/rebranded/deployed as needed.

**Comment by nolim1t** [comment]
I'd say keep it LNCM, and fork off from it whenever necessary. It worked for all the other shitcoins out there ;)

**Comment by meeDamian** [comment]
I'm adding a config and endpoint to invoicer that returns stuff needed to populate UI with proper data.

**Comment by nolim1t** [comment]
Lets put this into master for now?

Any objections **not** to?

**Comment by meeDamian** [comment]
Nope.

**Pull request merged**
